#!/bin/bash

mkdir -p /root/init-env
cd /root/init-env

# Redirect output to log file
exec &>>/root/init-env/init-env.log

printf "" >/root/init-env/init-env.status
echo "$(date)"
########## NO CHANGES ABOVE THIS LINE ##########

echo "### Creating workspace directory (cd into it in init-foreground, not here)"
mkdir /workspace
echo "### Finished creating workspace directory"
echo "### Installing stern CLI"
curl -Lo stern https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64 && chmod +x stern && sudo mv stern /usr/local/bin
echo "### Finished installing stern CLI"

########## NO CHANGES BELOW THIS LINE ##########
# The following must be the last line
echo "done" >> /root/init-env/init-env.status
